export const TRAFFIC = 'TRAFFIC';
export const GET_TRAFFIC = 'GET_TRAFFIC';
export const GET_TRAFFIC_RECEIVED = 'GET_TRAFFIC_RECEIVED';
export const GET_TRAFFIC_CANCELED = 'GET_TRAFFIC_CANCELED';
export const CLEAR_TRAFFIC = 'CLEAR_TRAFFIC';
