export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_RECEIVED = 'SIGN_UP_RECEIVED';
export const SIGN_UP_WITHOUT_VER = 'SIGN_UP_WITHOUT_VER';
export const SIGN_UP_WITHOUT_VER_RECEIVED = 'SIGN_UP_WITHOUT_VER_RECEIVED';
export const SIGN_UP_CANCELED = 'SIGN_UP_CANCELED';
