export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_ME = 'UPDATE_ME';

export const PROFILE_RECEIVED = 'PROFILE_RECEIVED';
export const PROFILE_CANCELED = 'PROFILE_CANCELED';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_RECEIVED = 'UPDATE_PROFILE_RECEIVED';
export const UPDATE_USER_PROFILE_RECEIVED = 'UPDATE_USER_PROFILE_RECEIVED';

export const GET_PENDING_COUNT = 'GET_PENDING_COUNT';
export const PENDING_COUNT_RECEIVED = 'PENDING_COUNT_RECEIVED';
