export const GET_LIST_DATA = 'GET_LIST_DATA';
export const LIST_DATA_RECEIVED = 'LIST_DATA_RECEIVED';
export const LIST_DATA_CANCELED = 'LIST_DATA_CANCELED';
export const UPDATE_LIST_DATA = 'UPDATE_LIST_DATA';
export const CLEAR_LIST_DATA = 'CLEAR_LIST_DATA';
