export const GET_ENTITIES = 'GET_ENTITIES';
export const ENTITIES_RECEIVED = 'ENTITIES_RECEIVED';
export const ENTITIES_CANCELED = 'ENTITIES_CANCELED';
export const CLEAN_ENTITIES = 'CLEAN_ENTITIES';

export const AVALIABLE_SENSOR = 'AVALIABLE_SENSOR';
export const AVALIABLE_SENSOR_RECEIVED = 'AVALIABLE_SENSOR_RECEIVED';
