export const GET_DEVICES_LIST = 'GET_DEVICES_LIST';
export const DEVICES_LIST_RECEIVED = 'DEVICES_LIST_RECEIVED';
export const DEVICES_LIST_CANCELED = 'DEVICES_LIST_CANCELED';
export const CLEAR_DEVICES_LIST = 'CLEAR_DEVICES_LIST';

export const ADD_NEW_DEVICE = 'ADD_NEW_DEVICE';
export const NEW_DEVICE_RECEIVED = 'NEW_DEVICE_RECEIVED';
export const EDIT_DEVICE = 'EDIT_DEVICE';
export const EDIT_DEVICE_RECEIVED = 'EDIT_DEVICE_RECEIVED';
export const DELETE_DEVICE = 'DELETE_DEVICE';
export const DELETE_DEVICE_RECEIVED = 'DELETE_DEVICE_RECEIVED';
