export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_WIDGET = 'REMOVE_WIDGET';
export const UPDATE_WIDGET = 'UPDATE_WIDGET';
export const UPDATE_LAYOUT = 'UPDATE_LAYOUT';
export const LOCK = 'LOCK';

export const GET_ONE_DASHBOARD = 'GET_ONE_DASHBOARD';
export const ONE_DASHBOARD_RECEIVED = 'ONE_DASHBOARD_RECEIVED';
export const ONE_DASHBOARD_CANCELED = 'ONE_DASHBOARD_CANCELED';
export const SAVE_DASHBOARD_SUCCESS = 'SAVE_DASHBOARD_SUCCESS';

export const CLEAN_LAYOUT = 'CLEAN_LAYOUT';


export const ADD_WIDGET = 'ADD_WIDGET';
export const ADD_WIDGET_RECEIVED = 'ADD_WIDGET_RECEIVED';
export const UPDATE_WIDGET_RECEIVED = 'UPDATE_WIDGET_RECEIVED';
export const REMOVE_WIDGET_RECEIVED = 'REMOVE_WIDGET_RECEIVED';

export const CANCEL_WIDGET = 'CANCEL_WIDGET';

export const TOGGLE_RELES = 'TOGGLE_RELES';

export const GET_WIDGET = 'GET_WIDGET';
export const GET_WIDGET_RECEIVED = 'GET_WIDGET_RECEIVED';

