export const GET_BAR_STATISTIC = 'GET_BAR_STATISTIC';
export const BAR_STATISTIC_RECEIVED = 'BAR_STATISTIC_RECEIVED';
export const BAR_STATISTIC_CANCEL = 'BAR_STATISTIC_CANCEL';
export const BAR_STATISTIC_CLEAR = 'BAR_STATISTIC_CLEAR';
