export const GET_DASHBOARDS_LIST = 'GET_DASHBOARDS_LIST';
export const DASHBOARDS_LIST_RECEIVED = 'DASHBOARDS_LIST_RECEIVED';
export const DASHBOARDS_LIST_CANCELED = 'DASHBOARDS_LIST_CANCELED';
export const CLEAR_DASHBOARDS_LIST = 'CLEAR_DASHBOARDS_LIST';

export const ADD_NEW_DASHBOARD = 'ADD_NEW_DASHBOARD';
export const NEW_DASHBOARD_RECEIVED = 'NEW_DASHBOARD_RECEIVED';
export const EDIT_DASHBOARD = 'EDIT_DASHBOARD';
export const EDIT_DASHBOARD_RECEIVED = 'EDIT_DASHBOARD_RECEIVED';
export const DELETE_DASHBOARD = 'DELETE_DASHBOARD';
export const DELETE_DASHBOARD_RECEIVED = 'DELETE_DASHBOARD_RECEIVED';
