export const GET_PAYMENTS_LIST = 'GET_PAYMENTS_LIST';
export const PAYMENTS_LIST_RECEIVED = 'PAYMENTS_LIST_RECEIVED';
export const PAYMENTS_LIST_CANCELED = 'PAYMENTS_LIST_CANCELED';
export const CLEAR_PAYMENTS_LIST = 'CLEAR_PAYMENTS_LIST';

export const GET_PUBLIC_KEY = 'GET_PUBLIC_KEY';
export const PUBLIC_KEY_RECEIVED = 'PUBLIC_KEY_RECEIVED';

export const SUBSCRIBED = 'SUBSCRIBED';
export const SUBSCRIBED_RECEIVED = 'SUBSCRIBED_RECEIVED';

export const UN_SUBSCRIBED = 'UN_SUBSCRIBED';
export const UN_SUBSCRIBED_RECEIVED = 'UN_SUBSCRIBED_RECEIVED';
