export const GET_SENSORS_LIST = 'GET_SENSORS_LIST';
export const SENSORS_LIST_RECEIVED = 'SENSORS_LIST_RECEIVED';
export const SENSORS_LIST_CANCELED = 'SENSORS_LIST_CANCELED';
export const CLEAR_SENSORS_LIST = 'CLEAR_SENSORS_LIST';

export const ADD_NEW_SENSOR = 'ADD_NEW_SENSOR';
export const NEW_SENSOR_RECEIVED = 'NEW_SENSOR_RECEIVED';
export const EDIT_SENSOR = 'EDIT_SENSOR';
export const EDIT_SENSOR_RECEIVED = 'EDIT_SENSOR_RECEIVED';
export const DELETE_SENSOR = 'DELETE_SENSOR';
export const DELETE_SENSOR_RECEIVED = 'DELETE_SENSOR_RECEIVED';
