export const ADD_NEW_ENTITY = 'ADD_NEW_ENTITY';
export const ADD_NEW_ENTITY_RECEIVED = 'ADD_NEW_ENTITY_RECEIVED';
export const ADD_NEW_ENTITY_CANCELED = 'ADD_NEW_ENTITY_CANCELED';

export const VIEW_ENTITY = 'VIEW_ENTITY';
export const VIEW_ENTITY_RECEIVED = 'VIEW_ENTITY_RECEIVED';

export const UPDATE_ENTITY = 'UPDATE_ENTITY';
export const UPDATE_ENTITY_RECEIVED = 'UPDATE_ENTITY_RECEIVED';

export const DELETE_ENTITY = 'DELETE_ENTITY';
export const DELETE_ENTITY_RECEIVED = 'DELETE_ENTITY_RECEIVED';

export const GET_ENTITY = 'GET_ENTITY';
export const GET_ENTITY_RECEIVED = 'GET_ENTITY_RECEIVED';

