export const GET_PLANS_LIST = 'GET_PLANS_LIST';
export const PLANS_LIST_RECEIVED = 'PLANS_LIST_RECEIVED';
export const PLANS_LIST_CANCELED = 'PLANS_LIST_CANCELED';
export const CLEAR_PLANS_LIST = 'CLEAR_PLANS_LIST';

export const ADD_NEW_PLAN = 'ADD_NEW_PLAN';
export const NEW_PLAN_RECEIVED = 'NEW_PLAN_RECEIVED';
export const EDIT_PLAN = 'EDIT_PLAN';
export const EDIT_PLAN_RECEIVED = 'EDIT_PLAN_RECEIVED';
export const DELETE_PLAN = 'DELETE_PLAN';
export const DELETE_PLAN_RECEIVED = 'DELETE_PLAN_RECEIVED';
