export const VIEW_COMPANY = 'VIEW_COMPANY';
export const VIEW_COMPANY_RECEIVED = 'VIEW_COMPANY_RECEIVED';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const UPDATE_COMPANY_RECEIVED = 'UPDATE_COMPANY_RECEIVED';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const DELETE_COMPANY_RECEIVED = 'DELETE_COMPANY_RECEIVED';
export const COMPANY_ERROR = 'COMPANY_ERROR';
export const UPDATE_COMPANY_STATUS = 'UPDATE_COMPANY_STATUS';
export const UPDATE_COMPANY_STATUS_RECEIVED = 'UPDATE_COMPANY_STATUS_RECEIVED';

export const DEFAULT_INDEX = 'DEFAULT_INDEX';

