export const REQUEST_FORGOT_EMAIL = 'REQUEST_FORGOT_EMAIL';
export const FORGOT_EMAIL_RECEIVED = 'FORGOT_EMAIL_RECEIVED';
export const FORGOT_EMAIL_CANCELED = 'FORGOT_EMAIL_CANCELED';

export const SEND_RESET_PASSWORD = 'SEND_RESET_PASSWORD';
export const RESET_PASSWORD_RECEIVED = 'RESET_PASSWORD_RECEIVED';
