export const GET_REPORTS_LIST = 'GET_REPORTS_LIST';
export const REPORTS_LIST_RECEIVED = 'REPORTS_LIST_RECEIVED';
export const REPORTS_LIST_CANCELED = 'REPORTS_LIST_CANCELED';
export const CLEAR_REPORTS_LIST = 'CLEAR_REPORTS_LIST';

export const DOWNLOAD_REPORTS_LIST = 'DOWNLOAD_REPORTS_LIST';
export const DOWNLOAD_REPORTS_LIST_RECEIVED = 'DOWNLOAD_REPORTS_LIST_RECEIVED';

