export const GET_TRANSACTIONS_LIST = 'GET_TRANSACTIONS_LIST';
export const TRANSACTIONS_LIST_RECEIVED = 'TRANSACTIONS_LIST_RECEIVED';
export const TRANSACTIONS_LIST_CANCELED = 'TRANSACTIONS_LIST_CANCELED';
export const CLEAR_TRANSACTIONS_LIST = 'CLEAR_TRANSACTIONS_LIST';
